### PR TITLE
finishing pipeline and a few related changes in tl_classifier. tested…

### PR DESCRIPTION
**Pull request by shreyanshbhatt**
Code for calling tl_classifier from tl_detector. A few changes (details in comments) in tl_classifier. It appears to be working.

### CODE REVIEW

**Comment by siva1729** [comment]
Code changes look fine except thinking of scenario of real life Traffic Light where we could get more than
one TL in a image with different colors (ex: Red for left-going, GREEN for straight/right-going traffic).
In that case we need to decide which TL/color to chose ? I haven't had a chance to run the simulator yet witht the changes..will do

Need check the ROS bag images if there are any such scenarios of more than 1 TL in a image..

**Comment by shreyanshbhatt** [comment]
Hello Sreedhar,
We consider that situation as an "error" and I believe it can be handled by STATE_COUNT_THRESHOLD. Consider the following scenario of light turning from red to yellow,
- The light is currently red, Hence we are in state 0 (indicating red light)
- The light starts turning to the yellow and we have both red and yellow light "on" at this moment. We can either get "yellow" as classifier output or red. If we get yellow, we will still be in the state 0 (as we have not got enough evidence = STATE_COUNT_THRESHOLD indicating it's time to move). If we get "red" as the output, we will still be in that state. In other words, we have a buffer of STATE_COUNT_THRESHOLD image frames where the lights can overlap and we don't change the state
- The light turns into yellow, we wait until we get enough evidence of the yellow light before we move.

So. I think the program should be able to deal with this situation.

**Comment by kenshiro-o** [comment]
Hey guys,

I think the code looks good. I am tempted to remove some of the commented lines as they make the code harder to read. I'll test on my Desktop tonight or tomorrow morning latest. Very good work!

Also I think Sreyansh is correct in stating that we use the `STATE_COUNT_THRESHOLD` variable to minimise false positives and ensure the model detected a given traffic light over enough multiple frames.

From my understanding, some self-driving car tech companies apply some sort of Kalman filter to stabilise the detection (I have no idea how to do this though 🤔 )

**Comment by shreyanshbhatt** [comment]
Thanks, Eddie,
Please go ahead, remove the comments and merge the branch.

I think the code works as it should for the highway track. However, I
noticed some issues with the rosbag dataset. It does not try to detect
traffic light sometime, probably because it does not get a list of upcoming
traffic light and stop line location. The car tries to stop at the
stop-line and if the stop-line information is not provided then it treats
as "no upcoming traffic light detected". Now, I did not do a thorough check
on this, i.e., whether the issue is missing information of stop line
location or something else or whether I used a correct ros-bag. However, if
you notice this happening (traffic light detection not invoked) then we
need to look into this. Also, we need to investigate whether the car
location is provided in the form that it is in the simulator. If there's a
mismatch, we need to consider that as well.

**Pull request merged**
